### ISSUE TITLE
Moving Run2UltraLegacy to master

### ISSUE THREAD

**Issue by sansan9401** [CMSSNU/SKFlatAnalyzer#139]
As many of use using UL branches, maybe it is time to move Run2UltraLegacy branch to master branch and old master (Run2Legacy) to another separated branch. Any opinion?

**Comment by jalmond** [comment]
I agree

**Comment by sihyunjeon** [comment]
+1

**Comment by sansan9401** [comment]
It is done. Now, old master branch become the Run2Legacy branch, and Run2UltraLegacy become master branch. Same for SKFlatMaker.
