### ISSUE TITLE
WP in Jet::IsTagged and FatJet::IsTagged

### ISSUE THREAD

**Issue by bhoh** [CMSSNU/SKFlatAnalyzer#33]
Btagging WPs are hard coded in **Jet.C** and **FatJet.C**.
But these are valid only for 2017.
I think it has a potential to cause a mistake. 
How about removing "**IsTagged**" method?
or changing like this?

```
bool Jet::IsTagged(Tagger tg, double wp){
  double tr = GetTaggerResult(tg);
  return (tr>wp);
}
```
or should we think more clever way?

(https://github.com/CMSSNU/SKFlatAnalyzer/blob/master/DataFormats/src/Jet.C#L126-L180)
(https://github.com/CMSSNU/SKFlatAnalyzer/blob/master/DataFormats/src/FatJet.C#L140-L194)

**Comment by jedori0228** [comment]
You can update https://github.com/CMSSNU/SKFlatAnalyzer/blob/3d54d9afbabf5494af9d7033c8d600914b7830c1/data/Run2Legacy_v1/2017/BTag/taggermap.txt#L1-L10 and try to use BTagSFUtil I think..?

**Comment by jalmond** [comment]
These files should be up to date, if not you should update the values/taggers and make a PR. 

To use it in your code, you can follow the recipe in Example run. 

https://github.com/CMSSNU/SKFlatAnalyzer/blob/master/Analyzers/src/ExampleRun.C#L48

https://github.com/CMSSNU/SKFlatAnalyzer/blob/master/Analyzers/src/ExampleRun.C#L336

Maybe the function in Jet class can be removed tio avoid confusion.

**Comment by bhoh** [comment]
**Jet::IsTagged** is used once in https://github.com/CMSSNU/SKFlatAnalyzer/blob/master/Analyzers/src/SKFlatValidation.C#L161.
It's okay to use for 2017, but it returns wrong result for other than 2017.
After changing that part like **ExampleRun.C**, we can remove **Jet::IsTagged and FatJet::IsTagged**. 

(https://github.com/CMSSNU/SKFlatAnalyzer/blob/master/DataFormats/src/Jet.C#L126-L180)
(https://github.com/CMSSNU/SKFlatAnalyzer/blob/master/DataFormats/src/FatJet.C#L140-L194)

If you guys agree with that idea, I could make a pull request.

**Comment by bhoh** [comment]
> Btagging WPs are hard coded in **Jet.C** and **FatJet.C**.
> But these are valid only for 2017.
> I think it has a potential to cause a mistake.
> How about removing "**IsTagged**" method?
> or changing like this?
> 
> ```
> bool Jet::IsTagged(Tagger tg, double wp){
>   double tr = GetTaggerResult(tg);
>   return (tr>wp);
> }
> ```
> 
> or should we think more clever way?

(https://github.com/CMSSNU/SKFlatAnalyzer/blob/master/DataFormats/src/Jet.C#L126-L180)
(https://github.com/CMSSNU/SKFlatAnalyzer/blob/master/DataFormats/src/FatJet.C#L140-L194)

**Comment by jalmond** [comment]
I think this is ok to make the pull request.

**Comment by jedori0228** [comment]
Please check #37

**Comment by bhoh** [comment]
> Please check #37

it looks good!

**Comment by jedori0228** [comment]
#37 merged.
